### ISSUE TITLE
[Feature] Create code of conduct

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Comic-book-button-anim#10]
## Feature description

Add a CODE_OF_CONDUCT.md file to the project

**Comment by Darainn** [comment]
@eduardconstantin assign me this issue

**Comment by eduardconstantin** [comment]
@Darainn are you still working on this?

**Comment by JuanitaCathy** [comment]
If this still needs work, i would like to work on it @eduardconstantin

**Comment by eduardconstantin** [comment]
@JuanitaCathy you can take it, you can find an example in my other projects

**Comment by JuanitaCathy** [comment]
Okay
