### ISSUE TITLE
[Feature] Create npm package

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Comic-book-button-anim#16]
I would like to create an NPM package for this button to be easier to use.

**Comment by aaheli8** [comment]
Can I work on this issue?

**Comment by eduardconstantin** [comment]
@aaheli8 Sure

**Comment by aaheli8** [comment]
Can I contribute? I was unassigned.

**Comment by eduardconstantin** [comment]
Are you still working on this issue?

**Comment by aaheli8** [comment]
Yes I am interested in working on this issue, I had a test so couldn't start.

**Comment by aaheli8** [comment]
Working on the issue.

**Comment by aaheli8** [comment]
@eduardconstantin  Update:
I created an npm package using storybook and rollup but when I tried running the package locally, it installed but when I imported it into another react app, the page is becoming blank.
I installed the local package using the npm link package name but when I am running the app it is blank. 

I am trying an alternative way of setting up an npm package and if you have any suggestions then please provide them.

**Comment by eduardconstantin** [comment]
I haven't done packages, I don't know what to tell you. Maybe you can find something on github. There should be a package just for the button.

**Comment by aaheli8** [comment]
yes, I am looking for solutions.

**Comment by aaheli8** [comment]
Finally, it worked, and I published it on npm. I installed the package from npm into a project and could use it as a component in the react app.
![image](https://user-images.githubusercontent.com/66815283/195893598-e29016ec-6755-4cd9-b0c0-dc52adc59339.png)
I published the package on npm from my account for testing.
![image](https://user-images.githubusercontent.com/66815283/195894044-83c27f39-6fbb-427a-aab5-f5f7d5ce0064.png)

**Comment by eduardconstantin** [comment]
Awesome! Good job!

**Comment by aaheli8** [comment]
I created the npm package in a new folder so will I create a pull request in the main branch or there will be a separate branch for npm package?

**Comment by eduardconstantin** [comment]
probably another branch, let me check first

**Comment by eduardconstantin** [comment]
@aaheli8 you can use this branch: npm-pkg

**Comment by aaheli8** [comment]
Okay
