### ISSUE TITLE
[Feature] Create pull request template

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Comic-book-button-anim#19]
Create a PULL_REQUEST_TEMPLATE.md file to make code validation easier.

A guide can be found [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by frey0-0** [comment]
@eduardconstantin I would like to make this template

**Comment by asad0206** [comment]
Can I create the template for you ? Can you assign it to me for create a PR template

**Comment by eduardconstantin** [comment]
@asad0206 if @Frey0-0 can't do it, you can try

**Comment by frey0-0** [comment]
@eduardconstantin raised a PR for this issue. Please review.
