### ISSUE TITLE
[Feature] Write unit test

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Comic-book-button-anim#26]
**Is your feature request related to a problem? Please describe.**
This component doesn't have a unit test written.

**Describe the solution you'd like**
Write a unit test for the button component using jest

**Comment by ranjankuldeep** [comment]
I Want to work on this.
please assign it to me.
@eduardconstantin

**Comment by kumarharshh** [comment]
Hi, can you please assign this issue to me as I'm very eager to work on it?

**Comment by eduardconstantin** [comment]
@kumarharshh did you manage to write the test?
