### ISSUE TITLE
[Feature] Add counter

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Comic-book-button-anim#27]
**Is your feature request related to a problem? Please describe.**
Right now the button doesn't do any action.

**Describe the solution you'd like**
Add a counter bellow the button that increments on every click on the button.
The font family should be the same with the one on the button.
The state of the counter should be in App.js, not inside the button component.

**Comment by najeebkp** [comment]
Hi @eduardconstantin please assign this to me
