### ISSUE TITLE
A footer with copyright details can be added. 

### ISSUE THREAD

**Issue by aditi10701** [eduardconstantin/Comic-book-button-anim#3]

**Comment by JagroopNatt** [comment]
please provide some details 
and assign this to me

**Comment by eduardconstantin** [comment]
@aditi10701 please add more details about this issue. Thank you!

**Comment by aditi10701** [comment]
a copyright section at the end which can make the project look more self.
a sample is attached.
![image](https://user-images.githubusercontent.com/98349669/194768895-fca823cf-f562-4197-b9bc-deed3f9ef870.png)
