### ISSUE TITLE
[Feature] Custom cursor when interacting with the button

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Comic-book-button-anim#6]
## Feature description

Create a custom design and animation for the cursor to be shown when:
- hovering over the button
- clicking on the button

The cursor design needs to have a comic book style.

**Comment by JuanitaCathy** [comment]
I can try.

**Comment by KhafiaAyyub** [comment]
@eduardconstantin  I would like to work on this issue, please assign this to me.

**Comment by eduardconstantin** [comment]
@KhafiaAyyub are you still working on this issue?

**Comment by Jam-Burger** [comment]
can you assign me this issue?
