### ISSUE TITLE
[Feature] Improve contribution section from readme

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Comic-book-button-anim#8]
## Feature description

Improve the contribution section from the readme file:
- Add how to contribute
- Add contributors

Also add a CONTRIBUTING.md file with contribution guidelines.

**Comment by cyberpvn7** [comment]
Assign me

**Comment by cyberpvn7** [comment]
### Done

#### How to Contribute:
![Screenshot (10)](https://user-images.githubusercontent.com/95903010/194751227-eba49636-7353-4d22-a64f-c1bc5b3bf8ba.png)

#### Dummey Contributors
![Screenshot (11)](https://user-images.githubusercontent.com/95903010/194751249-80d129fc-8009-440b-8a67-ba822f5e16bf.png)

#### And Guidline also Added

## I hope you like it

**_Thank You._**
