### ISSUE TITLE
[Feature] Add github stars on the page

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Comic-book-button-anim#9]
## Feature description

Add a github star button on the page, if possible add a comic book style to it.
![image](https://user-images.githubusercontent.com/9199763/194749478-de0b7eca-0c84-4765-afd8-660ad734d73d.png)

**Comment by amitroy-thedev** [comment]
Hey @eduardconstantin assign me this project I can give it a try

**Comment by eduardconstantin** [comment]
There you go!

**Comment by amitroy-thedev** [comment]
Hey @eduardconstantin do i need to use github api?

**Comment by amitroy-thedev** [comment]
I don't know reactjs but i can code with Html, css and javascript and github api

**Comment by eduardconstantin** [comment]
I think you can use this [Github buttons]( https://buttons.github.io)

**Comment by kushcoder12** [comment]
I would like to contribute.

**Comment by invarrow** [comment]
Which page? I dont see a link on the github..

**Comment by kushcoder12** [comment]
@eduardconstantin please review my PR.

**Comment by musavveer** [comment]
I would like to work on it

**Comment by musavveer** [comment]
@eduardconstantin Should i include the button on readme page?

**Comment by eduardconstantin** [comment]
> @eduardconstantin Should i include the button on readme page?

No, just in the application

**Comment by musavveer** [comment]
@eduardconstantin I have fixed the issue
